### ISSUE TITLE
Cloudant service unavailable issue.

### ISSUE THREAD

**Issue by muhammadali1233ify** [IBM-Cloud/secure-file-storage#2]
I have come across this issue with cloudant database in this implementation. After AppId has successfully redirected me to the front UI of application, it returns **unable to retrieve file list**. If i try to upload the file it says that **file upload failed**. I logged my running POD on the kubernetes cluster and found this error `"error":"service_unavailable","reason":"Service unavailable"` `error 503`. All of the service are provisioned in the us-south area but the kubernetes service is in us-east. The credential file is also created as a secret and these secrets are then bound to the application POD.
Amazing implementation from the architecture stand point by the way.
Thanks.

**Comment by data-henrik** [comment]
I assume you created all manually and not using the toolchain, correct? The Cloudant service credentials usually have the full URI and hence are accessible. Could you add further details, e.g., more log information?

**Comment by data-henrik** [comment]
closing this because of no updates
