### ISSUE TITLE
Update Cloudant credentials to use url instead of account

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/secure-file-storage#22]
Today we use the `username` but the better way is to use the url as this would also cover private endpoints.

However we need to make sure the Cloudant service instance is created with IAM credentials only as the URL thats includes user/password is incompatible with the use of IAM API key

FYI @VidyasagarMSC

**Comment by VidyasagarMSC** [comment]
Fixed in https://github.com/IBM-Cloud/secure-file-storage/commit/5f4c4dc2ba82d03c6890f315e221de4315912297
