### ISSUE TITLE
Deploy script fails to detect existing COS Lite instance

### ISSUE THREAD

**Issue by data-henrik** [IBM-Cloud/secure-file-storage#7]
I ran the toolchain with deployment to FRA. There is already a lite COS in the account and a COS instance named **secure-file-storage-cos**. 

```
####################################################################
#
# Cloud Object Storage
#
####################################################################

Creating service instance secure-file-storage-cos in resource group hloeser@de.ibm.com of account Uwe Fassnacht's Account as HLOESER@de.ibm.com...
FAILED
Error Code: RC-ServiceBrokerErrorResponse
Message: [409, Conflict] The account already has an instance created with the Lite plan.


Finished: FAILED
```
How about adding a field to the toolchain dialog to indicate whether to create a new COS instance or to pick from the existing ones for use in the toolchain?

**Comment by l2fprod** [comment]
@data-henrik 

the script checks if a service with this name already exists in the target resource group. Do you confirm there is already a COS service with the same name in the target resource group? If so then the script has a bug and should not have tried to create a service.

Assuming the service really does not exist in the resource group, we have a property to change the COS plan to `standard` in the job env properties.

Toolchain does not offer a way to pick existing services so it would be an open textfield and the user would need to enter the instance name or CRN and potentially the name of the resource group where the instance is if different from the one where she is deployed the sample. Sounds too much.

**Comment by data-henrik** [comment]
I saw that notice in the README under the toolchain section. That is something that could be moved up... Can it be set before the first deploy?

BTW: The deploy keeps failing for issues with some secrets.

**Comment by data-henrik** [comment]
closing it because the PR https://github.com/IBM-Cloud/secure-file-storage/pull/9 will address the failing deploys and README already has tip on Lite plan
